@extends('layouts.app')
@section('content')
{{-- https://api.checkwx.com/metar/EKYT,EKAH,EGPD,GCRR,GMAD,LEMG,LIEA,LEAL,OJAI,EHAM,LIPY,OJAQ,ESSA,LGAV,LEBL,LIBR,EDDB,LFRB,KBFI,LIME,EGBB,LFBZ,KBIS,EKBI,LIPE,LQBK,LFBD,EGHH,EDDW,LIBD,LKTB,EGGD,EBBR,LFSB,LZIB,KBTV,LHBP,LFOB,LFSL,EPBY,LFMU,LIEE,LFMK,LECH,LFLC,EDDK,LGSA,LIRA,LICB,LRCL,EKCH,EBCI,LIBC,LICC,LIMZ,KCWA,EGFF,LFGJ,EDLW,EIDW,KDVL,EGPH,LFBE,EHEH,EGNX,KERI,GMMI,EGTE,LPFR,KFAR,LIRF,GMFF,EDSB,EDJA,LFTW,EDDF,GCFV,EPGD,EGPF,LIMJ,ESGG,LEGE,EDDH,EFHK,EDFH,UKHH,LEIB,LYNI,UKBB,EIKY,EPKK,LZKZ,EPKT,EYKA,EGNM,EPLL,LFBT,EGKK,LFBL,LFQQ,LPPT,GCLP,EGGP,EFLP,LFBH,EGGW,ELLX,EPLB,UKLL,LFLL,LEMD,LEMH,EGCC,KMHT,KMKE,LMML,EGNV,ESMS,KMOT,LFML,EHBK,LIMC,LIRN,LFMN,EGNT,GMMW,EIKN,EGHQ,EDLV,LFRS,EDDN,UKOO,LROD,LPPR,EICK,ENGM,LKMT,LROP,GMFO,GMMZ,LPPD,LBPD,LIRZ,LCPH,LFMP,EGPK,LFBI,EYPA,LIMP,LEPA,LICJ,EPPO,KPQI,LKPR,LIRP,LIBP,KPWM,EGHL,GMMX,GMME,KRHI,EVRA,LEMI,EPRZ,KSBN,LRSB,LEST,LRSV,LEXJ,LGTS,EINN,LBSF,EGSS,LICA,LEZL,LOWS,EPSY,EPSC,LPLA,GCXO,GCTS,LYPG,EETN,LFBO,LLBG,EFTP,GMTT,LICT,ENTO,LIMF,LIPQ,LIPH,LRTR,GMTN,LFOT,KTVF,LIPZ,LEVX,LOWW,LEVT,LEVC,LEVD,EYVI,LIPX,ESOW,EPMO,EPWR,KWVL,LFOK,LEJR,KXWA,LDZA,LEZG/decoded --}}


<script>
var xhttp = new XMLHttpRequest();
xhttp.open("GET", "https://api.checkwx.com/metar/EKYT,EKAH,EGPD,GCRR,GMAD,LEMG,LIEA,LEAL,OJAI,EHAM,LIPY,OJAQ,ESSA,LGAV,LEBL,LIBR,EDDB,LFRB,KBFI,LIME,EGBB,LFBZ,KBIS,EKBI,LIPE,LQBK,LFBD,EGHH,EDDW,LIBD,LKTB,EGGD,EBBR,LFSB,LZIB,KBTV,LHBP,LFOB,LFSL,EPBY,LFMU,LIEE,LFMK,LECH,LFLC,EDDK,LGSA,LIRA,LICB,LRCL,EKCH,EBCI,LIBC,LICC,LIMZ,KCWA,EGFF,LFGJ,EDLW,EIDW,KDVL,EGPH,LFBE,EHEH,EGNX,KERI,GMMI,EGTE,LPFR,KFAR,LIRF,GMFF,EDSB,EDJA,LFTW,EDDF,GCFV,EPGD,EGPF,LIMJ,ESGG,LEGE,EDDH,EFHK,EDFH,UKHH,LEIB,LYNI,UKBB,EIKY,EPKK,LZKZ,EPKT,EYKA,EGNM,EPLL,LFBT,EGKK,LFBL,LFQQ,LPPT,GCLP,EGGP,EFLP,LFBH,EGGW,ELLX,EPLB,UKLL,LFLL,LEMD,LEMH,EGCC,KMHT,KMKE,LMML,EGNV,ESMS,KMOT,LFML,EHBK,LIMC,LIRN,LFMN,EGNT,GMMW,EIKN,EGHQ,EDLV,LFRS,EDDN,UKOO,LROD,LPPR,EICK,ENGM,LKMT,LROP,GMFO,GMMZ,LPPD,LBPD,LIRZ,LCPH,LFMP,EGPK,LFBI,EYPA,LIMP,LEPA,LICJ,EPPO,KPQI,LKPR,LIRP,LIBP,KPWM,EGHL,GMMX,GMME,KRHI,EVRA,LEMI,EPRZ,KSBN,LRSB,LEST,LRSV,LEXJ,LGTS,EINN,LBSF,EGSS,LICA,LEZL,LOWS,EPSY,EPSC,LPLA,GCXO,GCTS,LYPG,EETN,LFBO,LLBG,EFTP,GMTT,LICT,ENTO,LIMF,LIPQ,LIPH,LRTR,GMTN,LFOT,KTVF,LIPZ,LEVX,LOWW,LEVT,LEVC,LEVD,EYVI,LIPX,ESOW,EPMO,EPWR,KWVL,LFOK,LEJR,KXWA,LDZA,LEZG/decoded", true);
xhttp.setRequestHeader('X-API-Key', 'c7ec86f8437f41e9b1b5e68341');
xhttp.send();




xhttp.onreadystatechange = function() {
  if (this.readyState == 4 && this.status == 200) {
    metar_raw = JSON.parse(xhttp.responseText)
    metar = metar_raw.data

    for(let i = 0; i < metar.length; i++){
        weather = metar[i]
        if(weather.flight_category == "IFR" || weather.flight_category == "LIFR"){
            console.log(weather.icao);
        }
    }
  }
};


</script>


@endsection